language: tex
ubuntu-version: 14.04
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/
    trusty main restricted universe multiverse" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y -o Dpkg::Options::="--force-confnew" latexmk
  - sudo apt-get install -qq -y debconf texlive-base texlive-latex-extra texlive-fonts-extra latex-beamer texlive-lang-german texlive-fonts-recommended texlive-extra-utils cm-super wget
  - sudo apt-get install -qq lcdf-typetools
  - sudo apt-get install -qq tree
  - sudo apt-get install -qq poppler-utils
script:
  # Install uarial
  - wget https://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
  - sudo texlua install-getnonfreefonts
  - sudo getnonfreefonts-sys --verbose arial-urw
  # build tubslatex
  - make zip V=1
  # Install tubs theme
  - sudo unzip build/tubslatex_1.1.0.tds.zip -d /usr/share/texmf/
  - sudo mktexlsr &&
    sudo updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map &&
    sudo updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map &&
    sudo updmap-sys
  # test tubslatex
  #- cd regression-test &&
  #  ./new-test.sh
after_failure:
  - cat /tmp/tmp.*
