#! /bin/sh
# postinst script for latex-beamer
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

case "$1" in
    configure)

    logfile=$(mktemp -p /tmp texlive-tubs.XXXXXXXX)
    echo -n "Running mktexlsr..."
    if mktexlsr >> $logfile 2>&1; then
      echo "done."
    else 
      echo "failed. Output has been stored in"
      echo "$logfile"
      echo "Please include this file if you report a bug."
    fi

    echo -n "Checking fontmap..."
    if pdftexmap=`kpsewhich pdftex.map` >> $logfile 2>&1; then
      echo "done."
      echo "Found map file: $pdftexmap" >> $logfile
    else
      echo "failed. Output has been stored in"
      echo "$logfile"
      echo "Please include this file if you report a bug."
      exit 1
    fi
    
#    varlibmap=``
#    echo "varlibmap: $varlibmap"
    if [ -z `echo $pdftexmap | grep /var/lib` ]; then
      echo ""
      echo "Warning: You seem to use a local font map\n  ($pdftexmap)."
      echo "Only global font maps are supported in this installation"
      read -p "Do you want to delete local font map? [y/n]" yesno
      case $yesno in
        y|Y)
          echo -n "Deleting $pdftexmap..."
          rm -f $pdftexmap
          echo "done."
          ;;
        *)
          echo "You may need to run updmap manually after install!"
          ;;
      esac
    fi

    # Touch 10local.cfg to prevent errors of buggy updmap
    # TODO: This step might be skipped in texlive 201x
    mkdir -p /etc/texmf/updmap.d || true
    touch /etc/texmf/updmap.d/10local.cfg || true
      
    # Check for getnonfreefonts and install if needed
    # Is either located at /usr/bin/getnonfreefonts (as symlink)
    # or at /usr/local/bin/getnonfreefonts
    if ([ ! -x /usr/bin/getnonfreefonts ] && [ ! -x /usr/local/bin/getnonfreefonts ]); then
      echo ""
      echo "'getnonfreefonts' was not found on your system."
      echo "Do you want automatically download and install it? [y/n]"
      read yesno
      if [ $yesno = "y" ]; then
	echo -n "Downloading and installing getnonfreefonts..."
        if wget -P /tmp http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts >> $logfile 2>&1; then
          texlua /tmp/install-getnonfreefonts >> $logfile 2>&1
          rm -f /tmp/install-getnonfreefonts
	  echo "done."
        else
          echo "failed. Output has been stored in"
          echo "$logfile"
          echo "Please include this file if you report a bug."
          echo "-- You may need to install Arial later manually --"
        fi
      else
        echo "Warning: Arial will not be installed!"
        echo "-- You may need to install Arial later manually --"
      fi
    fi

    echo -n "Running getnonfreefonts to install arial-urw..."
    if getnonfreefonts --sys --verbose arial-urw >> $logfile 2>&1; then
      echo "done."
    else
      echo "failed. Output has been stored in"
      echo "$logfile"
      echo "Please include this file if you report a bug."
      echo "-- You may need to install Arial later manually --"
    fi

    # Check for already available Mapfiles
    # (Some updmap versions fail trying to enable an active map)
    npsans=`updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! | grep -v disabled || true`
    npserif=`updmap-sys --listmaps 2>&1 | grep NexusProSerif | grep -v ! | grep -v disabled || true`

    # Enable Nexus maps
    if [ -z "$npsans" ]; then
      echo -n "Adding map file for NexusProSans..."
      if updmap-sys --nomkmap --nohash --enable Map=NexusProSans.map >> $logfile 2>&1; then
        echo "done."
      else
        echo "failed.\n Output has been stored in"
        echo "$logfile"
        echo "Please include this file if you report a bug."
      fi
    else
      echo "NexusProSans already enabled, skipping."
    fi
    if [ -z "$npserif" ]; then
      echo -n "Adding map file for NexusProSerif..."
      if updmap-sys --nomkmap --nohash --enable Map=NexusProSerif.map >> $logfile 2>&1; then
        echo "done."
      else
        echo "failed.\n Output has been stored in"
        echo "$logfile"
        echo "Please include this file if you report a bug."
      fi
    else
      echo "NexusProSerif already enabled, skipping."
    fi

    # Run updmap to update font db
    echo -n "Running updmap-sys..."
    if updmap-sys >> $logfile 2>&1; then
      echo "done."
    else
      echo "failed. Output has been stored in"
      echo "$logfile"
      echo "Please include this file if you report a bug."
    fi
  ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.



exit 0
