#! /bin/sh
# postrm script for texlive-tubs
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge|remove|abort-install|abort-upgrade|disappear)
      logfile=$(mktemp -p /tmp texlive-tubs.XXXXXXXX)
      echo -n "Running mktexlsr..."
      if mktexlsr >> $logfile 2>&1; then
        echo "done."
      else 
        echo "failed. Output has been stored in"
        echo "$logfile"
        echo "Please include this file if you report a bug."
      fi

      echo -n "Removing map file for NexusProSans..."
      if updmap-sys --nomkmap --nohash --disable NexusProSans.map > $logfile 2>&1; then
	echo "done."
      else
        echo "failed."
      fi
      echo -n "Removing map file for NexusProSerif..."
      if updmap-sys --nomkmap --nohash --disable NexusProSerif.map > $logfile 2>&1; then
	echo "done."
      else
        echo "failed."
      fi

      echo -n "Running updmap-sys..."
      if updmap-sys > $logfile 2>&1; then
	echo "done."
      else
        echo "failed."
      fi
      
      echo "Output has been stored in $logfile"

    ;;
    upgrade|failed-upgrade)
        # nothing to to...
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac


exit 0
