#! /bin/sh
# postrm script for texlive-tubs
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge|remove|abort-install|abort-upgrade|disappear)
        if [ -x /usr/bin/mktexlsr ] ; then
            /usr/bin/mktexlsr
        fi
        if [ -x /usr/bin/kpsewhich ] ; then
            # Debugging output
            pdftexmap=`kpsewhich pdftex.map`
            echo "Found map file: $pdftexmap";
            # Select if to use local version
            varlibmap=`kpsewhich pdftex.map | grep /var/lib`
        else
            echo "kpsewhich not found. Aborting..."
            exit 1
        fi
        if [ -z "$varlibmap" ]; then
            echo "Removing local map file for NexusProSans..."
            /usr/bin/updmap --nomkmap --nohash --disable NexusProSans.map > /dev/null 2>&1 || true
            echo "Removing local map file for NexusProSerif..."
            /usr/bin/updmap --nomkmap --nohash --disable NexusProSerif.map > /dev/null 2>&1 || true
            echo "running updmap..."
            /usr/bin/updmap > /dev/null 2>&1 || true
        else
            echo "Removing map file for NexusProSans..."
            /usr/bin/updmap-sys --nomkmap --nohash --disable NexusProSans.map > /dev/null 2>&1 || true
            echo "Removing map file for NexusProSerif..."
            /usr/bin/updmap-sys --nomkmap --nohash --disable NexusProSerif.map > /dev/null 2>&1 || true
            echo "running updmap-sys..."
            /usr/bin/updmap-sys > /dev/null 2>&1 || true
        fi

    ;;
    upgrade|failed-upgrade)
        # nothing to to...
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac


exit 0
