#!/bin/bash

echo -e 'STEP0: \t Cleaning potential previous installations...'
rm -r tex
rm -r fonts
rm -r doc

REPODIR=../..
echo -e 'STEP1: \t Creating tex and doc directory structure...'
mkdir -p tex/latex/tubs
mkdir -p tex/latex/tubs/beamer
mkdir -p tex/latex/tubs/cd-base
mkdir -p tex/latex/tubs/report
mkdir -p tex/latex/tubs/nexus
mkdir -p doc/latex/tubs
mkdir -p doc/latex/tubs/beamer
mkdir -p doc/latex/tubs/cd-base
mkdir -p doc/latex/tubs/report
mkdir -p doc/latex/tubs/nexus

echo -e 'STEP2: \t Copying package files...'
echo -e '\t -> cd-base'
cp $REPODIR/cd-base/src/*.sty tex/latex/tubs/cd-base/.
cp $REPODIR/cd-base/src/*.pdf tex/latex/tubs/cd-base/.
cp -r $REPODIR/cd-base/src/logos tex/latex/tubs/cd-base/.
echo -e '\t -> beamer'
cp $REPODIR/beamer/src/*.sty  tex/latex/tubs/beamer/.
cp $REPODIR/beamer/src/defaulttitlepicture.jpg tex/latex/tubs/beamer/.
echo -e '\t -> report'
cp $REPODIR/report/src/*.cls  tex/latex/tubs/report/.
cp $REPODIR/report/src/*.tex  tex/latex/tubs/report/.
echo -e '\t -> nexus'
cp $REPODIR/nexus/src/*.sty   tex/latex/tubs/nexus/.
cp $REPODIR/nexus/src/*.fd    tex/latex/tubs/nexus/.

echo -e 'STEP3: \t copying doc files'
cp $REPODIR/cd-base/doc/tubscolors/*.pdf  doc/latex/tubs/cd-base/.
cp $REPODIR/cd-base/doc/tubslogo/*.pdf    doc/latex/tubs/cd-base/.
cp $REPODIR/nexus/doc/*.pdf               doc/latex/tubs/nexus/.
cp $REPODIR/beamer/doc/*.pdf              doc/latex/tubs/beamer/.


OTFDEFAULT="--warn-missing --encoding=texnansx --feature=kern --feature=liga --feature=lnum --force"

cp $REPODIR/nexus/otf-src/*.otf .

if [ -x /usr/bin/otftotfm ]
then
echo -e 'STEP4: \t creating font files...'
# Serif
echo -e '\t -> Serif'
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Regular $OTFDEFAULT --map-file=NexusProSerif.map NexusSerifPro-Regular.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Italic $OTFDEFAULT --map-file=NexusProSerif.map NexusSerifPro-Italic.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-SmallCaps  $OTFDEFAULT --feature=smcp --map-file=NexusProSerif.map NexusSerifPro-Regular.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Slanted --slant=.167  $OTFDEFAULT  --map-file=NexusProSerif.map NexusSerifPro-Regular.otf 

otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Bold-Regular  $OTFDEFAULT --map-file=NexusProSerif.map NexusSerifPro-Bold.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Bold-Italic $OTFDEFAULT --map-file=NexusProSerif.map NexusSerifPro-BoldItalic.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Bold-SmallCaps  $OTFDEFAULT --feature=smcp --map-file=NexusProSerif.map NexusSerifPro-Bold.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSerif-Bold-Slanted --slant=.167  $OTFDEFAULT --map-file=NexusProSerif.map NexusSerifPro-Bold.otf 

# Sans Serif
echo -e '\t -> Sans Serif'
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Regular  $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-Regular.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Italic $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-Italic.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-SmallCaps  $OTFDEFAULT --feature=smcp --map-file=NexusProSans.map NexusSansPro-Regular.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Slanted --slant=.167  $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-Regular.otf 

otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Bold-Regular  $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-Bold.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Bold-Italic $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-BoldItalic.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Bold-SmallCaps  $OTFDEFAULT --feature=smcp --map-file=NexusProSans.map NexusSansPro-Bold.otf 
otftotfm --no-updmap --vendor=Fontshop --name=NexusProSans-Bold-Slanted --slant=.167  $OTFDEFAULT --map-file=NexusProSans.map NexusSansPro-Bold.otf

# Move generated fonts
echo -e 'STEP 5: \t Copying font files...'
mkdir -p fonts/enc/dvips/Fontshop/
mv *.enc fonts/enc/dvips/Fontshop/

mkdir -p fonts/map/
mv *.map fonts/map/

mkdir -p fonts/tfm/Nexus/
mv *.tfm fonts/tfm/Nexus/

mkdir -p fonts/vf/Nexus/
mv *.vf  fonts/vf/Nexus/

mkdir -p fonts/type1/Nexus/
mv *.pfb fonts/type1/Nexus/

else

echo -e 'Command otftofm not found. Skipping...'

fi

rm *.otf
